-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 18:12:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airly
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airly
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airly` DEFAULT CHARACTER SET utf8 ;
USE `airly` ;

-- -----------------------------------------------------
-- Table `airly`.`sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airly`.`sensors` (
  `id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
